#include <iostream>
#include <cmath> // For std::abs
#include <unsupported/Eigen/Polynomials> // Required for Eigen's polynomial solver

int main() {
    return 0;
}

// This function was generated by AI partially. I just tested it and it works
// HOWEVER, this function will not be included in the GPU code anyways, and I thought it was better to use an outside library for now since I can debug other 
// parts of my program
std::vector<double> quartic_calculator(double a, double, b, double c, double d, double e) {
	std::vector<double> real_roots(10);
	 // Eigen expects coefficients from lowest degree to highest: e, d, c, b, a
    Eigen::VectorXd coeffs(5);
    coeffs << e, d, c, b, a; 

    Eigen::PolynomialSolver<double, Eigen::Dynamic> solver;
    solver.compute(coeffs);

    // Get the roots using 'auto' to avoid complex type scoping
    const auto& roots = solver.roots();
	int j = 0
    std::cout << "Real roots (Wave speeds): " << std::endl;
    for (int i = 0; i < roots.size(); ++i) {
        // Safe floating-point comparison using a small threshold (e.g., 1e-9)
        if (std::abs(roots[i].imag()) < 1e-9 && roots[i].real < 1 && roots[i].real > -1) { 
			real_roots[j] = roots[i].real();
			j++;
        }
    }

	return real_roots;
}